# Generated by Django 3.2.9 on 2021-11-10 17:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('type', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slides', djongo.models.fields.ArrayField(model_container=api.models.Slide)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slideshows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
